import { join } from "path";
import { fileURLToPath } from "url";

import { runFixtures } from "./helpers.mjs";

const __dirname = fileURLToPath(new URL(".", import.meta.url));

runFixtures("Convert JSX", join(__dirname, "__dom_fixtures__"), {
  moduleName: "r-dom",
  builtIns: ["For", "Show"],
  generate: "dynamic",
  renderers: [
    {
      name: "dom",
      moduleName: "r-dom",
      elements: [
        "table",
        "tbody",
        "div",
        "h1",
        "span",
        "header",
        "footer",
        "slot",
        "my-el",
        "my-element",
        "module",
        "input",
        "img",
        "iframe",
        "button",
        "a",
        "svg",
        "rect",
        "x",
        "y",
        "linearGradient",
        "stop",
        "style",
        "li",
        "ul",
        "label",
        "text",
        "namespace:tag",
        "p",
        "noscript",
        "select",
        "option",
        // mathml
        "math",
        "annotation",
        "annotation-xml",
        "maction",
        "merror",
        "mfrac",
        "mi",
        "mmultiscripts",
        "mn",
        "mo",
        "mover",
        "mpadded",
        "mphantom",
        "mprescripts",
        "mroot",
        "mrow",
        "ms",
        "mspace",
        "msqrt",
        "mstyle",
        "msub",
        "msubsup",
        "msup",
        "mtable",
        "mtd",
        "mtext",
        "mtr",
        "munder",
        "munderover",
        "semantics",
        "menclose",
        "mfenced",
      ],
    },
  ],
  staticMarker: "@once",
  contextToCustomElements: true,
  wrapConditionals: true,
});
